insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXDESTINATION","String",100,"The destination name the order is to be routed too. Not relevant on the Core",1);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("START_TIME","Long",7527,"the time to start working and order represented in UTC",2);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("END_TIME","Long",7662,"the time to stop working and order represented in UTC",3);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("PRICE","Price",44,"the price represented as a long",4);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("MAXFLOOR","Integer",111,"The maximum quantity to display to the floor",5);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("STYLE","String",7681,"Experts/Rules - PASSIVE, NORMAL, AGGRESSIVE, or, for US only, SUPER-AGGRESSIVE",6);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("TARGET_PARTICIPATION_RATE","Price",7543,"1-100 in percent, Newport 3 Rules use PCTVOLUME",7);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("PCTVOLUME","Price",7502,"1-100 in percent, used by Newport 3 Rules, Experts interprets this tag to mean TARGET_PARTICIPATION_RATE",8);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("MAX_PARTICIPATION_RATE","Price",7664,"0-100 in percent",9);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("MIN_PARTICIPATION_RATE","Price",7663,"0-100 in percent",10);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("FLOATING_LIMIT","String",7600,"LAST - Last price as limit None AVG - Average price as limit None VWAP - VWAP as limit (from arrival time) None REL - Relative return limit price (US only) Percent STR - Straight return limit price (US only) Percent MKT - Market adjusted limit price (US only) Price QUOTE - Aggressive quote return limit price (in bps) (US only) Integer",11);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("MKTADJ_LIMIT_SYMBOL","String",7536,"Any valid US Symbol",12);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("MKTADJ_LIMIT_TIME","Long",7537,"a time represented in UTC",13);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("MKTADJ_LIMIT_PRICE","Price",7538,"Price or Percent based on LimitType",14);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("IWOULD_PRICE","Price",7539,"(US Only)",15);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("SLOPE","Integer",7688,"-100 to 100 (default is 0) (US Only)",16);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("INCLUDE_CLOSE","Byte",7540,"Y/N",17);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("BENCHMARK","String",7621,"OPEN or CLOSE (mutually exclusive with BenchmarkPrice)",18);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("BENCHMARK_PRICE","Price",7756,"(mutually exclusive with Benchmark)",19);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("MUST_COMPLETE","Byte",7541,"Y/N (US Only)",20);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("AUCTION_ENABLED","Byte",7736,"Y/N (EU & AS)",21);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("BUCKETID","String",7749,"10-character max unique name",22);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("CASH_BALANCE","Price",7669,"Positive for raise cash (sell) Negative for spend cash (buy)",23);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("CASH_LIMIT","Price",7627,"Amount you’re willing to trade in a positive direction above the cash constraint. Narrower ranges may hinder trading behavior.",24);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("LOWER_LIMIT_VALUE","Price",7637,"Amount you’re willing to trade in a negative direction below the cash constraint. Narrower ranges may hinder trading behavior.",25);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("INITIALIZATION_METHOD","String",7793,"IMM - Immediately",26);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("INVESTOR_ID","String",7684,"QFII ID for Taiwan and Korea",27);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("RULE80A","Byte",47,"A, K, or J,",28);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_TRIGGER_VALUE","Price",7571,"4-digit precision; target spread ratio or log ratio",29);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("MAX_PARTICIPATION_RATE2","Price",7665,"0-100",30);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_INIT_SIDE","String",7572,"“Buy”, ”Sell”, or ”SellShort”",31);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_USE_SELL_PRICE","String",7573,"“BID”, “ASK”, “LAST”",32);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_USE_BUY_PRICE","String",7574,"“BID”, “ASK”, “LAST”",33);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_TRIGGER_METHOD","String",7575,"RBS - Ratio (B/S) RSB - Ratio (S/B) SBS - Spread (B-S) SSB - Spread (S-B) LBS - Log Ratio (ln(B/S)) LSB - Log Ratio (ln(S/B))",34);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_TRIGGER_DIRECTION","String",7576,"“GT” or “LT”",35);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_BUY_TERMS_RATIO","Price",7577,"4-digit precision; default value should be set to 1",36);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_SELL_TERMS_RATIO","Price",7579,"4-digit precision; default value should be set to 1",37);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_BUY_TERMS_CASH","Price",7578,"Default value should be set to 0",38);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_SELL_TERMS_CASH","Price",7580,"Default value should be set to 0",39);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_WORK_PASSIVE_SIDE","Byte",7582,"Y/N",40);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_WORK_INSIDE","Byte",7583,"Y/N",41);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_IOC_INIT_SIDE","Byte",7584,"Y/N",42);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_MAX_SUB_DOLLARS","Price",7585,"Maximum allowed to submit at any one point in time; should be a positive, non-zero value",43);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXPERT_PAIR_MAINTAIN_SHARE_RATIO","Byte",7581,"Y/N",44);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("REVISE_INTERVAL_MIN","Integer",7596,"Minimum of random interval of time to wait between revisions of order currently exposed",45);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("REVISE_INTERVAL_MAX","Integer",7597,"Maximum of random interval of time to wait between revisions of order currently exposed",46);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("RELOAD_INTERVAL_MIN","Integer",7598,"Minimum of random interval of time to wait between submissions to destination",47);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("RELOAD_INTERVAL_MAX","Integer",7599,"Maximum of random interval of time to wait between submissions to destination",48);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("DISPLAY_QUOTE_MULTIPLE","Price",7632,"quoted price",49);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("MORE_PASSIVE","Boolean",7608,"Y/N",50);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("TICKS_AGGRESSIVE","Integer",7686,"Number of ticks over which to adjust the price aggressively",51);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("PCT_AGGRESSIVE","Price",7680,"Percent to adjust the required price aggressively",52);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("INCLUDE_ALL_VOL","Boolean",7738,"Y/N",53);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("URGENCY","Price",7530,"0-10",54);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("TICKS_AGGRESSIVE1","Price",7689,"0-10",55);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("RISK_ACCEPTANCE_PARAMETER","Price",7747,"0-10",56);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("USE_OPTIMIZED_PARTRATE","Boolean",7531,"Y/N",57);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("AUTO_CALC_RATE","Boolean",7532,"Y/N",58);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("AUTO_REFRESH_RATE","Boolean",7533,"Y/N",59);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("MIN_QTY","Integer",110,"The minimum amount of shares the order can execute at",60);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("BLOCK_SIZE_TO_IGNORE","Integer",7687,"Ignore any block size greater than X when calculating volume consideration",61);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("CBX_ELIGABLE","Boolean",7676,"Y/N",62);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("AMORTISE","Boolean",7615,"Y/N",63);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("AUCTION_CATCHUP","Boolean",7737,"Y/N",64);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("AVERAGE_DOWN","Boolean",7631,"Y/N",65);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("CBX_DISPLAY","String",7670,"Free form String with CBX display instructions for Algos",66);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("CBX_HIDDEN","Boolean",7702,"Y/N",67);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("DISABLE_OFF_EXCHANGE","Boolean",7674,"Y/N",68);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("ECN_DISPLAY","Boolean",7675,"Y/N",69);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("ECN_ONLY","Boolean",7542,"Y/N",70);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EXTENDED_REPORTING","Boolean",7647,"Y/N",71);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("IDX_ELIGIBLE","Boolean",7507,"Y/N",72);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("IGNORE_MARKET_DATA_STATUS","Boolean",7623,"Y/N",73);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("INDEX_ARB_TYPE","Boolean",7739,"Y/N",74);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("IS_MOC","Boolean",7624,"Y/N",75);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("IS_MOO","Boolean",7733,"Y/N",76);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("IS_TIMED_RELEASE","Boolean",7751,"Y/N",77);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("IS_TWAP","Boolean",7602,"Y/N",78);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("JX_ELIGIBLE","Boolean",7685,"Y/N",79);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("CUSTOMERORIGINATED","Boolean",6218,"if value is CUSTOMER then set 6218=Y otherwise 6218=N",80);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("OPEN_ELIGIBLE","Boolean",7679,"Y/N",81);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("ORDER_VISIBILITY","Byte",7782,"VTMFOrderVisibility values B=BuySide, S=SellSide, A=All, M=MarketMaker, D=Dark",82);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("PRIMARY_DISPLAY","String",7612,"Free form String",83);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("RISK_AVERSION","String",7703,"Free form String",84);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("ROUNDING","String",7634,"Free form String",85);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("SCHEDULE","String",7633,"Free form String",86);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("SCHEDULE_DISCRETION","String",7682,"Free form String",87);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("SMRT_REROUTEABLE","Byte",6516,"R - Allow Reroute, N - Don’t Allow Reroute",88);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("TRACKING_DISCRETION","String",7683,"Free form String",89);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("ANONYMOUS","Boolean",6223,"Y/N",90);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("USE_CLIENT_ID","Boolean",976,"Y/N",91);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("USE_DYNAMIC_RATECALC","Boolean",7534,"Y/N",92);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("WORK_ACTIVELY","Boolean",7658,"Y/N",94);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("EX_PARTNER_ID","String",3509,"The Exchange PartnerID",95);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("IGNORE_WARNING","Boolean",3508,"Y/N",96);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("PAIRED_SYMBOL","String",7750,"This is where the user should enter the symbol that they wish to track. They can enter INDEX if they want to pair against a benchmark index for the stock. We will expect InetSymbol for now. We may want to change this in the future to convert client's symbology.",97);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("PAIRED_SYMBOL_BENCHMARK","String",7755,"This is where the client can specify a benchmark for the paired symbol for the rule to track to. The options are as follows: - Ask - Bid -Floating Last -Floating VWAP -Last Trade -Market -Mid Price -None -Primary -VWAP",98);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("Expert Override Volume Pattern","String",7561,"If specified, this field needs to match the ID Source delivered in tag 22. If the client delivers an invalid symbol, the Expert should reject the order back to the client. Experts will use this field as a reference symbology profile.",99);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("Target Completion","Integer",7783,"Target Completion for Asian Algos.",100);
insert into vtmf (vtmf_name,vtmf_type,vtmf_tag,vtmf_notes,fix_id) values ("Sweep Book","Boolean",7784,"Sweep Book for Asian Algos.",101);
